# BoxCast Plugin by RedShaunia Box of Rocks
# Version 1.0

BoxCastReload: 'BoxCast Reloaded'
DisplayBirthday: '&3The Servers Birthday is the 20th of June 2016'
DisplayDonate: '&3Donate here &bhttp://boxofrocks.net/shop'
DisplayEmail: '&3The server Email is &bcontact@BoxOfRocks.net'
DisplayForum: '&3Forum websites is at &bwww.boxofrocks.net/forum'
DisplayIP: '&3The server Ip is &bplay.boxofrocks.net'
DisplayTS: '&3Teamspeak3 server &bplay.BoxOfRocks.net &bPassword BOX987'
DisplayTwitch: '&3Twitch channel &https://www.twitch.tv/redshaunia'
DisplayTwitter: 'Coming Soon'
DisplayWebsite: '&3Server websites &bhttp://boxofrocks.net/'
DisplayYoutube: '&3Box Of Rocks Youtube channel https://www.youtube.com/channel/UCvcW3E5Iszr5wBJPcnNk8gA'
DisplayClaiming: '&3Land Claiming &bhttps://goo.gl/yC12Oj'
DisplayGitHub: '&3Box of Rocks GitHub https://github.com/RedShaunia'
DisplayRules: Server Rules
    No Hacking.     
    No Spam or excessive Caps.     
    No Griefing
    No AFK machines. Auto kill is allowed
    No Cheating
    No Exploiting
    No Trolling
    No Advertising
    No Extreme Language
    