main: io.github.RedShaunia.boxcast.BoxCast
version: 1.0
name: BoxCast

commands:
  display:
    description: All kinds of server information
  boxcastreload:
    usage: /<command>
    description: Reload BoxCast Config
    